# Meta Data for SEO

## Homepage
title = "OWASP Coraza"
titleSeparator = "-"
titleAddition = "Enterprise-grade open source web application firewall library"
description = "OWASP Coraza is an enterprise-grade, open-source, and high-performance Web Application Firewall library ready to protect your beloved applications."

# Alert
alert = true
alertDismissable = true
alertText = "Coraza v3 will be available soon, <a href=\"https://github.com/corazawaf/coraza/issues/336\">stay tuned!</a>"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "coraza.io"
titleHome = "OWASP Coraza"

## Twitter Cards
twitterSite = "@corazatech"
twitterCreator = "@jptosso"

## JSON-LD
# schemaType = "Organization"
schemaType = "Person"
schemaName = "OWASP oraza WAF"
schemaAuthor = "Juan Pablo Tosso"
schemaAuthorTwitter = "https://twitter.com/jptosso"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/jptosso/"
schemaAuthorGitHub = "https://github.com/corazawaf"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/jptosso"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/corazawaf/coraza"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by a lot of love ❤️ (and code) - By Juan Pablo Tosso"
copyRight = ""

# Edit Page
docsRepo = "https://github.com/jptosso/coraza.io"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = true